export interface PiattoData {
  id: string;
  nome: string;
  descrizione: string;
  prezzo: string;
  imageUrl: string;
  categoria: string;
  ingredienti?: string;
  allergeni?: string;
}

export const PIATTI: PiattoData[] = [
  {
    id: "ant-1",
    nome: "Bruschetta alla Brace",
    categoria: "Antipasti",
    prezzo: "€9",
    descrizione: "Pane di casa grigliato sulla brace con pomodorini confit, aglio, basilico e olio EVO di Puglia.",
    imageUrl: "https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Pane, pomodorini, aglio, basilico, olio EVO",
    allergeni: "Glutine",
  },
  {
    id: "ant-2",
    nome: "Gamberi Flambé",
    categoria: "Antipasti",
    prezzo: "€16",
    descrizione: "Gamberi rossi di Mazara saltati con brandy, aglio, peperoncino e prezzemolo. Fiamma e sale.",
    imageUrl: "https://images.unsplash.com/photo-1559737558-2f5a35f4523b?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Gamberi, brandy, aglio, peperoncino, prezzemolo",
    allergeni: "Crostacei",
  },
  {
    id: "ant-3",
    nome: "Burrata con Pomodorini Confit",
    categoria: "Antipasti",
    prezzo: "€13",
    descrizione: "Burrata di Andria con pomodorini confit al forno, origano selvatico e riduzione balsamica.",
    imageUrl: "https://images.unsplash.com/photo-1571091655789-405eb7a3a3a8?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Burrata, pomodorini, origano, aceto balsamico",
    allergeni: "Latticini",
  },
  {
    id: "ant-4",
    nome: "Carpaccio di Manzo",
    categoria: "Antipasti",
    prezzo: "€15",
    descrizione: "Controfiletto battuto a mano con rucola selvatica, scaglie di parmigiano e limone di Sicilia.",
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Manzo, rucola, parmigiano, limone",
    allergeni: "Latticini",
  },
  {
    id: "ant-5",
    nome: "Salsicce alla Brace",
    categoria: "Antipasti",
    prezzo: "€11",
    descrizione: "Salsicce artigianali al finocchietto grigliate su carbone di quercia. Serve con senape rustica.",
    imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Maiale, finocchietto, pepe, senape",
    allergeni: "Glutine",
  },
  {
    id: "pri-1",
    nome: "Rigatoni al Ragù di Brace",
    categoria: "Primi",
    prezzo: "€16",
    descrizione: "Ragù di manzo e maiale cotto lentamente sul fuoco basso per sei ore. Rigatoni trafilati al bronzo.",
    imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Rigatoni, manzo, maiale, pomodoro, vino rosso",
    allergeni: "Glutine",
  },
  {
    id: "pri-2",
    nome: "Tagliatelle al Tartufo Nero",
    categoria: "Primi",
    prezzo: "€22",
    descrizione: "Tagliatelle all'uovo con tartufo nero di Norcia, burro fuso e parmigiano stagionato 36 mesi.",
    imageUrl: "https://images.unsplash.com/photo-1612874742237-6526221588e3?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Tagliatelle, tartufo nero, burro, parmigiano",
    allergeni: "Glutine, uova, latticini",
  },
  {
    id: "pri-3",
    nome: "Risotto al Vino Rosso",
    categoria: "Primi",
    prezzo: "€18",
    descrizione: "Riso Carnaroli mantecato con Barolo, midollo di bue e grana padano. Comfort da camino.",
    imageUrl: "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Riso Carnaroli, Barolo, midollo, grana padano",
    allergeni: "Latticini",
  },
  {
    id: "pri-4",
    nome: "Pappardelle al Cinghiale",
    categoria: "Primi",
    prezzo: "€19",
    descrizione: "Pappardelle larghissime con ragù di cinghiale marinato al Montepulciano, bacche di ginepro.",
    imageUrl: "https://images.unsplash.com/photo-1567608285969-48e4bbe0d399?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Pappardelle, cinghiale, Montepulciano, ginepro",
    allergeni: "Glutine",
  },
  {
    id: "pri-5",
    nome: "Spaghetti all'Arrabbiata",
    categoria: "Primi",
    prezzo: "€14",
    descrizione: "Spaghetti con pomodoro San Marzano, aglio, peperoncino calabrese e basilico fresco. Piccante.",
    imageUrl: "https://images.unsplash.com/photo-1516100882582-96c3a05fe590?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Spaghetti, pomodoro, aglio, peperoncino calabrese",
    allergeni: "Glutine",
  },
  {
    id: "sec-1",
    nome: "Costata alla Brace",
    categoria: "Secondi",
    prezzo: "€42",
    descrizione: "Rib-eye da 400g maturato 30 giorni, grigliato su carbone di faggio. Sale Maldon, olio a crudo.",
    imageUrl: "https://images.unsplash.com/photo-1558030006-450675393462?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Manzo Frisona, sale Maldon, olio EVO",
    allergeni: "Nessuno",
  },
  {
    id: "sec-2",
    nome: "Pollo alla Diavola",
    categoria: "Secondi",
    prezzo: "€20",
    descrizione: "Pollo spatchcock marinato con peperoncino, rosmarino e limone. Grigliato piatto e croccante.",
    imageUrl: "https://images.unsplash.com/photo-1518492104633-130d0cc84637?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Pollo, peperoncino, rosmarino, limone",
    allergeni: "Nessuno",
  },
  {
    id: "sec-3",
    nome: "Agnello alla Brace",
    categoria: "Secondi",
    prezzo: "€28",
    descrizione: "Cosciotto d'agnello disossato con chimichurri di erbe fresche. Cotto lento sulla brace.",
    imageUrl: "https://images.unsplash.com/photo-1574484284002-952d92456975?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Agnello, prezzemolo, origano, aglio, aceto",
    allergeni: "Nessuno",
  },
  {
    id: "sec-4",
    nome: "Braciola di Maiale",
    categoria: "Secondi",
    prezzo: "€22",
    descrizione: "Braciola di maiale iberico con salvia, burro nocciola e mela verde caramellata alla brace.",
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Maiale iberico, salvia, burro, mela",
    allergeni: "Latticini",
  },
  {
    id: "sec-5",
    nome: "Polpo alla Brace",
    categoria: "Secondi",
    prezzo: "€24",
    descrizione: "Polpo verace prima cotto sottovuoto poi grigliato alla brace. Patate schiacciate con 'nduja.",
    imageUrl: "https://images.unsplash.com/photo-1559737558-2f5a35f4523b?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Polpo, patate, 'nduja, olio EVO",
    allergeni: "Molluschi",
  },
  {
    id: "dol-1",
    nome: "Semifreddo al Caffè",
    categoria: "Dolci",
    prezzo: "€8",
    descrizione: "Semifreddo all'espresso con croccante di nocciole e scaglie di cioccolato fondente 72%.",
    imageUrl: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Panna, caffè, nocciole, cioccolato fondente",
    allergeni: "Uova, latticini, frutta a guscio",
  },
  {
    id: "dol-2",
    nome: "Panna Cotta al Caramello Salato",
    categoria: "Dolci",
    prezzo: "€7",
    descrizione: "Panna cotta vellutata con caramello al sale di Cervia e granella di pistacchio di Bronte.",
    imageUrl: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Panna, gelatina, zucchero, sale, pistacchio",
    allergeni: "Latticini, frutta a guscio",
  },
  {
    id: "dol-3",
    nome: "Brownie al Cioccolato",
    categoria: "Dolci",
    prezzo: "€8",
    descrizione: "Brownie caldo con cuore fondente, gelato alla vaniglia bourbon e coulis di lamponi.",
    imageUrl: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Cioccolato fondente, burro, uova, farina",
    allergeni: "Glutine, uova, latticini",
  },
  {
    id: "dol-4",
    nome: "Crème Brûlée alla Vaniglia",
    categoria: "Dolci",
    prezzo: "€7",
    descrizione: "Crema alla vaniglia del Madagascar con crosta di zucchero caramellata al cannello.",
    imageUrl: "https://images.unsplash.com/photo-1519915028121-7d3463d20b13?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Panna, uova, vaniglia, zucchero",
    allergeni: "Uova, latticini",
  },
  {
    id: "dol-5",
    nome: "Tiramisù della Brace",
    categoria: "Dolci",
    prezzo: "€7",
    descrizione: "Tiramisù al caffè di torrefazione con mascarpone della casa, scaglie di cioccolato affumicato.",
    imageUrl: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Mascarpone, uova, savoiardi, caffè, cioccolato",
    allergeni: "Uova, latticini, glutine",
  },
  {
    id: "vin-1",
    nome: "Barolo DOCG",
    categoria: "Vini",
    prezzo: "€58/b",
    descrizione: "Re dei vini piemontesi. Nebbiolo tannico e complesso delle Langhe. Ideale con la costata.",
    imageUrl: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Nebbiolo — Langhe, Piemonte",
  },
  {
    id: "vin-2",
    nome: "Brunello di Montalcino DOCG",
    categoria: "Vini",
    prezzo: "€72/b",
    descrizione: "Sangiovese Grosso di Montalcino. Struttura maestosa, finale eterno. Per l'agnello.",
    imageUrl: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Sangiovese Grosso — Montalcino, Toscana",
  },
  {
    id: "vin-3",
    nome: "Chianti Classico Riserva",
    categoria: "Vini",
    prezzo: "€36/b",
    descrizione: "Gallo Nero nel bicchiere. Ciliegia, spezie, cuoio. Versatile con tutta la brace.",
    imageUrl: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Sangiovese — Greve in Chianti, Toscana",
  },
  {
    id: "vin-4",
    nome: "Montepulciano d'Abruzzo",
    categoria: "Vini",
    prezzo: "€26/b",
    descrizione: "Rosso abruzzese potente e morbido. Frutto nero, rovere tostato. Ottimo rapporto qualità-prezzo.",
    imageUrl: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Montepulciano — Abruzzo",
  },
  {
    id: "vin-5",
    nome: "Vermentino di Sardegna DOC",
    categoria: "Vini",
    prezzo: "€22/b",
    descrizione: "Bianco minerale e sapido della Gallura. Perfetto con i gamberi e il polpo.",
    imageUrl: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Vermentino — Gallura, Sardegna",
  },
];

export const GALLERY_IMAGES = [
  "https://images.unsplash.com/photo-1558030006-450675393462?w=800&auto=format&fit=crop&q=80",
  "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&auto=format&fit=crop&q=80",
  "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=80",
  "https://images.unsplash.com/photo-1516100882582-96c3a05fe590?w=800&auto=format&fit=crop&q=80",
  "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&auto=format&fit=crop&q=80",
];

export const HERO_IMAGE =
  "https://images.unsplash.com/photo-1558030006-450675393462?w=1600&auto=format&fit=crop&q=80";
