export interface PiattoData {
  id: string;
  nome: string;
  descrizione: string;
  prezzo: string;
  imageUrl: string;
  categoria: string;
  ingredienti?: string;
  allergeni?: string;
}

export const PIATTI: PiattoData[] = [
  {
    id: "ant-1",
    nome: "Carciofi alla Romana",
    categoria: "Antipasti",
    prezzo: "€12",
    descrizione: "Carciofi romani teneri brasati con aglio, mentuccia e olio extravergine. Ricetta della tradizione.",
    imageUrl: "https://images.unsplash.com/photo-1574484284002-952d92456975?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Carciofi, aglio, mentuccia, olio EVO",
    allergeni: "Nessuno",
  },
  {
    id: "ant-2",
    nome: "Supplì al Telefono",
    categoria: "Antipasti",
    prezzo: "€8",
    descrizione: "Supplì fritti con riso al ragù e mozzarella filante. Il filo di mozzarella è il nostro marchio.",
    imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Riso, ragù, mozzarella, uova, pangrattato",
    allergeni: "Glutine, uova, latticini",
  },
  {
    id: "ant-3",
    nome: "Fiori di Zucca Fritti",
    categoria: "Antipasti",
    prezzo: "€10",
    descrizione: "Fiori di zucca ripieni di mozzarella e acciuga, in pastella croccante. Classico romano immancabile.",
    imageUrl: "https://images.unsplash.com/photo-1596797882870-8c33d938b2b4?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Fiori di zucca, mozzarella, acciuga, farina, olio",
    allergeni: "Glutine, latticini, pesce",
  },
  {
    id: "ant-4",
    nome: "Bruschetta al Pomodoro",
    categoria: "Antipasti",
    prezzo: "€7",
    descrizione: "Pane di casa tostato sfregato con aglio, pomodori di stagione e basilico. Semplicità assoluta.",
    imageUrl: "https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Pane, pomodoro, aglio, basilico, olio EVO",
    allergeni: "Glutine",
  },
  {
    id: "ant-5",
    nome: "Mortadella e Burrata",
    categoria: "Antipasti",
    prezzo: "€11",
    descrizione: "Mortadella IGP di Bologna con burrata fresca e pistacchi di Bronte. Affettata al momento.",
    imageUrl: "https://images.unsplash.com/photo-1567101948523-eb4f45f5c7ad?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Mortadella, burrata, pistacchi",
    allergeni: "Latticini, frutta a guscio",
  },
  {
    id: "pri-1",
    nome: "Cacio e Pepe",
    categoria: "Primi",
    prezzo: "€14",
    descrizione: "Tonnarelli con pecorino romano DOP e pepe nero macinato al momento. Nient'altro.",
    imageUrl: "https://images.unsplash.com/photo-1612874742237-6526221588e3?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Tonnarelli, pecorino romano DOP, pepe nero",
    allergeni: "Glutine, latticini",
  },
  {
    id: "pri-2",
    nome: "Carbonara della Tradizione",
    categoria: "Primi",
    prezzo: "€15",
    descrizione: "Rigatoni con guanciale croccante, uovo intero, pecorino e pepe. Zero panna — come vuole Roma.",
    imageUrl: "https://images.unsplash.com/photo-1612874742237-6526221588e3?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Rigatoni, guanciale, uovo, pecorino, pepe",
    allergeni: "Glutine, uova, latticini",
  },
  {
    id: "pri-3",
    nome: "Amatriciana",
    categoria: "Primi",
    prezzo: "€14",
    descrizione: "Bucatini con guanciale, pomodoro San Marzano, pecorino e peperoncino. La matrice di tutto.",
    imageUrl: "https://images.unsplash.com/photo-1567608285969-48e4bbe0d399?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Bucatini, guanciale, pomodoro, pecorino, peperoncino",
    allergeni: "Glutine, latticini",
  },
  {
    id: "pri-4",
    nome: "Gricia",
    categoria: "Primi",
    prezzo: "€14",
    descrizione: "La carbonara bianca: rigatoni con guanciale dorato, pecorino cremoso e pepe abbondante.",
    imageUrl: "https://images.unsplash.com/photo-1516100882582-96c3a05fe590?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Rigatoni, guanciale, pecorino romano, pepe nero",
    allergeni: "Glutine, latticini",
  },
  {
    id: "pri-5",
    nome: "Pasta e Ceci",
    categoria: "Primi",
    prezzo: "€12",
    descrizione: "Pasta mista corta con ceci lessi nel brodo di rosmarino, pomodoro e aglio. Cucina povera nobile.",
    imageUrl: "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Pasta mista, ceci, rosmarino, aglio, pomodoro",
    allergeni: "Glutine",
  },
  {
    id: "sec-1",
    nome: "Abbacchio alla Scottadito",
    categoria: "Secondi",
    prezzo: "€22",
    descrizione: "Costolette di agnello alla brace, da mangiare con le mani. Scottante come il nome dice.",
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Agnello, rosmarino, aglio, olio EVO",
    allergeni: "Nessuno",
  },
  {
    id: "sec-2",
    nome: "Pollo alla Romana",
    categoria: "Secondi",
    prezzo: "€18",
    descrizione: "Pollo in umido con peperoni rossi e gialli, pomodoro e vino bianco. Piatto della domenica.",
    imageUrl: "https://images.unsplash.com/photo-1518492104633-130d0cc84637?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Pollo, peperoni, pomodoro, vino bianco",
    allergeni: "Nessuno",
  },
  {
    id: "sec-3",
    nome: "Saltimbocca alla Romana",
    categoria: "Secondi",
    prezzo: "€20",
    descrizione: "Scaloppine di vitello con prosciutto crudo e salvia, sfumate al vino bianco. Eleganza in padella.",
    imageUrl: "https://images.unsplash.com/photo-1574484284002-952d92456975?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Vitello, prosciutto crudo, salvia, vino bianco",
    allergeni: "Nessuno",
  },
  {
    id: "sec-4",
    nome: "Trippa alla Romana",
    categoria: "Secondi",
    prezzo: "€16",
    descrizione: "Trippa di vitello in salsa di pomodoro con mentuccia e pecorino grattugiato. Il piatto del sabato.",
    imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Trippa, pomodoro, mentuccia, pecorino",
    allergeni: "Latticini",
  },
  {
    id: "sec-5",
    nome: "Baccalà in Guazzetto",
    categoria: "Secondi",
    prezzo: "€19",
    descrizione: "Baccalà dissalato cotto nel sugo di pomodoro con olive nere, capperi e prezzemolo. Venerdì santo.",
    imageUrl: "https://images.unsplash.com/photo-1559737558-2f5a35f4523b?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Baccalà, pomodoro, olive, capperi, prezzemolo",
    allergeni: "Pesce",
  },
  {
    id: "dol-1",
    nome: "Tiramisù della Casa",
    categoria: "Dolci",
    prezzo: "€7",
    descrizione: "Preparato la mattina con mascarpone fresco, savoiardi e caffè ristretto. La nonna lo approva.",
    imageUrl: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Mascarpone, uova, savoiardi, caffè, cacao",
    allergeni: "Uova, latticini, glutine",
  },
  {
    id: "dol-2",
    nome: "Crostata di Ricotta",
    categoria: "Dolci",
    prezzo: "€6",
    descrizione: "Frolla croccante con crema di ricotta romana e scorza d'arancia. Semplice, perfetta.",
    imageUrl: "https://images.unsplash.com/photo-1519915028121-7d3463d20b13?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Ricotta, farina, burro, uova, arancia",
    allergeni: "Uova, latticini, glutine",
  },
  {
    id: "dol-3",
    nome: "Panna Cotta al Caramello",
    categoria: "Dolci",
    prezzo: "€6",
    descrizione: "Panna cotta vellutata con caramello amaro e sale di Cervia. Trema appena sul cucchiaio.",
    imageUrl: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Panna, gelatina, zucchero, sale",
    allergeni: "Latticini",
  },
  {
    id: "dol-4",
    nome: "Cannoli di Ricotta",
    categoria: "Dolci",
    prezzo: "€7",
    descrizione: "Cannoli croccanti con ricotta di pecora dolce, canditi e gocce di cioccolato. Due per porzione.",
    imageUrl: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Ricotta di pecora, cannolo, canditi, cioccolato",
    allergeni: "Glutine, latticini",
  },
  {
    id: "dol-5",
    nome: "Gelato Artigianale",
    categoria: "Dolci",
    prezzo: "€5",
    descrizione: "Tre palline dei gusti del giorno — produzione propria. Chiedere al cameriere le gusti disponibili.",
    imageUrl: "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Latte, panna, frutta di stagione",
    allergeni: "Latticini, uova",
  },
  {
    id: "vin-1",
    nome: "Frascati DOC",
    categoria: "Vini",
    prezzo: "€18/b",
    descrizione: "Bianco dei Castelli Romani. Fresco, leggero, minerale. Il vino dell'osteria per eccellenza.",
    imageUrl: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Malvasia, Trebbiano — Castelli Romani",
  },
  {
    id: "vin-2",
    nome: "Cesanese del Piglio DOCG",
    categoria: "Vini",
    prezzo: "€24/b",
    descrizione: "Rosso laziale DOCG, tannico e speziato. Si sposa perfettamente con l'abbacchio.",
    imageUrl: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Cesanese — Frosinone, Lazio",
  },
  {
    id: "vin-3",
    nome: "Prosecco di Valdobbiadene DOC",
    categoria: "Vini",
    prezzo: "€20/b",
    descrizione: "Spumante Glera delle colline patrimonio UNESCO. Bollicine fini, perlage persistente.",
    imageUrl: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Glera — Valdobbiadene, Veneto",
  },
  {
    id: "vin-4",
    nome: "Chianti Classico DOCG",
    categoria: "Vini",
    prezzo: "€26/b",
    descrizione: "Sangiovese toscano con ciliegia e viola. Struttura elegante, tannini gentili. Per la trippa.",
    imageUrl: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Sangiovese — Greve in Chianti, Toscana",
  },
  {
    id: "vin-5",
    nome: "Verdicchio dei Castelli di Jesi",
    categoria: "Vini",
    prezzo: "€19/b",
    descrizione: "Bianco marchigiano sapido e agrumato. Ideale con il baccalà e i carciofi.",
    imageUrl: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600&auto=format&fit=crop&q=80",
    ingredienti: "Verdicchio — Jesi, Marche",
  },
];

export const GALLERY_IMAGES = [
  "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&auto=format&fit=crop&q=80",
  "https://images.unsplash.com/photo-1424847651672-bf20a4b0982b?w=800&auto=format&fit=crop&q=80",
  "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&auto=format&fit=crop&q=80",
  "https://images.unsplash.com/photo-1567608285969-48e4bbe0d399?w=800&auto=format&fit=crop&q=80",
  "https://images.unsplash.com/photo-1596797882870-8c33d938b2b4?w=800&auto=format&fit=crop&q=80",
];

export const PARALLAX_IMAGE =
  "https://images.unsplash.com/photo-1514190051997-0f6f39ca5cde?w=1600&auto=format&fit=crop&q=80";
